# Generated by Django 5.2.6 on 2025-10-04 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_email_otp_user_email_verified_user_phone_otp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='aadhaar_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='aadhaar_verified',
            field=models.BooleanField(default=False),
        ),
    ]
