# Generated by Django 5.2.6 on 2025-11-09 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_paniclog_aadhaar_number_paniclog_contact_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paniclog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RemoveField(
            model_name='paniclog',
            name='aadhaar_number',
        ),
        migrations.RemoveField(
            model_name='paniclog',
            name='email',
        ),
        migrations.RemoveField(
            model_name='paniclog',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='paniclog',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paniclog',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='paniclog',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='paniclog',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='paniclog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
