# Generated by Django 5.2.6 on 2025-11-09 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_paniclog_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paniclog',
            name='contact_number',
        ),
        migrations.AddField(
            model_name='paniclog',
            name='snapshot_aadhaar',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='paniclog',
            name='snapshot_contact',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='paniclog',
            name='snapshot_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='paniclog',
            name='snapshot_full_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='paniclog',
            name='snapshot_profile_pic',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paniclog',
            name='snapshot_username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
