# Generated by Django 5.2.6 on 2025-11-09 18:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0008_remove_paniclog_contact_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='helplinecontact',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='paniclog',
            name='request_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paniclog',
            name='user_agent',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_responder',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='aadhaar_number',
            field=models.CharField(help_text='12 digit Aadhaar number', max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='Aadhaar number must be exactly 12 digits.', regex='^\\d{12}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='contact_number',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='user_default', max_length=150, unique=True),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='paniclog',
            index=models.Index(fields=['-timestamp'], name='core_panicl_timesta_16050c_idx'),
        ),
        migrations.AddIndex(
            model_name='paniclog',
            index=models.Index(fields=['latitude', 'longitude'], name='core_panicl_latitud_586679_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['aadhaar_number'], name='core_user_aadhaar_cd16f7_idx'),
        ),
    ]
