"""
Django settings for womensafety project.
Generated by 'django-admin startproject' using Django 5.2.6.
"""

import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent


# Helper function
def str2bool(v):
    return str(v).lower() in ("1", "true", "yes")


# ---------------------------------------------------------------------
# SECRET / DEBUG / HOSTS
# ---------------------------------------------------------------------
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-dev-placeholder-please-change"
)

DEBUG = str2bool(os.environ.get("DJANGO_DEBUG", "True"))

ALLOWED_HOSTS = [
    "127.0.0.1",
    "localhost",
    ".onrender.com",
]


# Dashboard passcode
DASHBOARD_PASSCODE = os.environ.get(
    "DASHBOARD_PASSCODE",
    "MyVerySecretCode123!"
)


# ---------------------------------------------------------------------
# Application definition
# ---------------------------------------------------------------------
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Local app
    "core",

    # Third party
    "rest_framework",
]

AUTH_USER_MODEL = "core.User"


# ---------------------------------------------------------------------
# Middleware
# ---------------------------------------------------------------------
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",

    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


ROOT_URLCONF = "womensafety.urls"


# ---------------------------------------------------------------------
# Templates
# ---------------------------------------------------------------------
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


WSGI_APPLICATION = "womensafety.wsgi.application"


# ---------------------------------------------------------------------
# Database
# ---------------------------------------------------------------------
DATABASES = {
    "default": {
        "ENGINE": os.environ.get(
            "DJANGO_DB_ENGINE",
            "django.db.backends.sqlite3"
        ),
        "NAME": os.environ.get(
            "DJANGO_DB_NAME",
            BASE_DIR / "db.sqlite3"
        ),
    }
}


# ---------------------------------------------------------------------
# Password validation
# ---------------------------------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"
    },
]


# ---------------------------------------------------------------------
# Internationalization
# ---------------------------------------------------------------------
LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Kolkata"

USE_I18N = True

USE_TZ = True


# ---------------------------------------------------------------------
# Static files
# ---------------------------------------------------------------------
STATIC_URL = "/static/"

STATICFILES_DIRS = [
    BASE_DIR / "core" / "static"
]

STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_STORAGE = (
    "whitenoise.storage.CompressedManifestStaticFilesStorage"
)


# ---------------------------------------------------------------------
# Media files
# ---------------------------------------------------------------------
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"


# ---------------------------------------------------------------------
# Authentication
# ---------------------------------------------------------------------
LOGIN_URL = "/login/"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"

SESSION_COOKIE_AGE = int(
    os.environ.get("DJANGO_SESSION_AGE", 60 * 60 * 3)
)

SESSION_SAVE_EVERY_REQUEST = True


# ---------------------------------------------------------------------
# Security
# ---------------------------------------------------------------------
CSRF_COOKIE_SECURE = str2bool(
    os.environ.get("DJANGO_CSRF_SECURE", "False")
)

SESSION_COOKIE_SECURE = str2bool(
    os.environ.get("DJANGO_SESSION_SECURE", "False")
)

SECURE_SSL_REDIRECT = str2bool(
    os.environ.get("DJANGO_SECURE_SSL_REDIRECT", "False")
)

SECURE_HSTS_SECONDS = int(
    os.environ.get("DJANGO_HSTS_SECONDS", 0)
)

SECURE_HSTS_INCLUDE_SUBDOMAINS = str2bool(
    os.environ.get("DJANGO_HSTS_INCLUDE_SUBDOMAINS", "False")
)

SECURE_HSTS_PRELOAD = str2bool(
    os.environ.get("DJANGO_HSTS_PRELOAD", "False")
)

# Render HTTPS support
SECURE_PROXY_SSL_HEADER = (
    "HTTP_X_FORWARDED_PROTO",
    "https"
)


# ---------------------------------------------------------------------
# Email
# ---------------------------------------------------------------------
EMAIL_BACKEND = os.environ.get(
    "DJANGO_EMAIL_BACKEND",
    "django.core.mail.backends.smtp.EmailBackend"
)

EMAIL_HOST = os.environ.get("DJANGO_EMAIL_HOST", "")
EMAIL_PORT = int(os.environ.get("DJANGO_EMAIL_PORT", 587) or 587)

EMAIL_HOST_USER = os.environ.get("DJANGO_EMAIL_USER", "")
EMAIL_HOST_PASSWORD = os.environ.get("DJANGO_EMAIL_PASSWORD", "")

EMAIL_USE_TLS = str2bool(
    os.environ.get("DJANGO_EMAIL_USE_TLS", "True")
)

DEFAULT_FROM_EMAIL = os.environ.get(
    "DJANGO_DEFAULT_FROM_EMAIL",
    "noreply@example.com"
)


# ---------------------------------------------------------------------
# Django REST Framework
# ---------------------------------------------------------------------
REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.AllowAny",
    ],
}


# ---------------------------------------------------------------------
# Default primary key field type
# ---------------------------------------------------------------------
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"