"""
Django settings for womensafety project.

Generated by 'django-admin startproject' using Django 5.2.6.
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# helper to read booleans from env
def str2bool(v):
    return str(v).lower() in ("1", "true", "yes")

# ---------------------------------------------------------------------
# SECRET / DEBUG / HOSTS
# ---------------------------------------------------------------------
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-dev-placeholder-please-change')
DEBUG = str2bool(os.environ.get('DJANGO_DEBUG', 'True'))

# ALLOWED_HOSTS: allow localhost for dev unless explicitly set via env
_default_hosts = ['127.0.0.1', 'localhost']
_allowed_env = os.environ.get('DJANGO_ALLOWED_HOSTS', '')
if _allowed_env:
    ALLOWED_HOSTS = [h.strip() for h in _allowed_env.split(',') if h.strip()]
else:
    ALLOWED_HOSTS = _default_hosts

# Always include dev hosts when DEBUG=True
if DEBUG:
    for h in _default_hosts:
        if h not in ALLOWED_HOSTS:
            ALLOWED_HOSTS.append(h)

# Dashboard passcode (use an env var in production)
DASHBOARD_PASSCODE = os.environ.get('DASHBOARD_PASSCODE', 'MyVerySecretCode123!')

# ---------------------------------------------------------------------
# Application definition
# ---------------------------------------------------------------------
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # local apps
    'core',

    # third party
    'rest_framework',
]

# custom user model
AUTH_USER_MODEL = 'core.User'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'womensafety.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'womensafety.wsgi.application'

# ---------------------------------------------------------------------
# Database (sqlite for dev; override with env in production)
# ---------------------------------------------------------------------
DATABASES = {
    'default': {
        'ENGINE': os.environ.get('DJANGO_DB_ENGINE', 'django.db.backends.sqlite3'),
        'NAME': os.environ.get('DJANGO_DB_NAME', BASE_DIR / 'db.sqlite3'),
    }
}

# ---------------------------------------------------------------------
# Password validation
# ---------------------------------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',},
]

# ---------------------------------------------------------------------
# Internationalization / Timezone
# ---------------------------------------------------------------------
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Kolkata'
USE_I18N = True
USE_TZ = True

# ---------------------------------------------------------------------
# Static & Media
# ---------------------------------------------------------------------
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "core" / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# ---------------------------------------------------------------------
# Authentication / Sessions
# ---------------------------------------------------------------------
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'
SESSION_COOKIE_AGE = int(os.environ.get('DJANGO_SESSION_AGE', 60 * 60 * 3))  # 3 hours default
SESSION_SAVE_EVERY_REQUEST = True

# ---------------------------------------------------------------------
# Security flags (turn on in production; controlled by env)
# ---------------------------------------------------------------------
CSRF_COOKIE_SECURE = str2bool(os.environ.get('DJANGO_CSRF_SECURE', 'False'))
SESSION_COOKIE_SECURE = str2bool(os.environ.get('DJANGO_SESSION_SECURE', 'False'))
SECURE_SSL_REDIRECT = str2bool(os.environ.get('DJANGO_SECURE_SSL_REDIRECT', 'False'))
SECURE_HSTS_SECONDS = int(os.environ.get('DJANGO_HSTS_SECONDS', 0))
SECURE_HSTS_INCLUDE_SUBDOMAINS = str2bool(os.environ.get('DJANGO_HSTS_INCLUDE_SUBDOMAINS', 'False'))
SECURE_HSTS_PRELOAD = str2bool(os.environ.get('DJANGO_HSTS_PRELOAD', 'False'))

# ---------------------------------------------------------------------
# Email (placeholders - set env vars in production)
# ---------------------------------------------------------------------
EMAIL_BACKEND = os.environ.get('DJANGO_EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.environ.get('DJANGO_EMAIL_HOST', '')
EMAIL_PORT = int(os.environ.get('DJANGO_EMAIL_PORT', 587) or 587)
EMAIL_HOST_USER = os.environ.get('DJANGO_EMAIL_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('DJANGO_EMAIL_PASSWORD', '')
EMAIL_USE_TLS = str2bool(os.environ.get('DJANGO_EMAIL_USE_TLS', 'True'))
DEFAULT_FROM_EMAIL = os.environ.get('DJANGO_DEFAULT_FROM_EMAIL', 'noreply@example.com')

# ---------------------------------------------------------------------
# Django Rest Framework (optional defaults)
# ---------------------------------------------------------------------
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
}

# ---------------------------------------------------------------------
# Default primary key field type
# ---------------------------------------------------------------------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
